#!/bin/bash

# For the license, see the LICENSE file in the root directory.
#set -x

if [ "$(id -u)" -ne 0 ]; then
	echo "Need to be root to run this test."
	exit 77
fi

DIR=$(dirname "$0")
ROOT=${DIR}/..
SWTPM=swtpm_cuse
SWTPM_EXE=$ROOT/src/swtpm/$SWTPM
CUSE_TPM_IOCTL=$ROOT/src/swtpm_ioctl/swtpm_ioctl
VTPM_NAME="vtpm-test-tpm2-locality"
export TPM_PATH=$(mktemp -d)
STATE_FILE=$TPM_PATH/tpm2-00.permall
VOLATILE_STATE_FILE=$TPM_PATH/tpm2-00.volatilestate

function cleanup()
{
	pid=$(ps aux | grep $SWTPM | grep -E "$VTPM_NAME\$" | gawk '{print $2}')
	if [ -n "$pid" ]; then
		kill -9 $pid
	fi
	rm -rf $TPM_PATH
}

trap "cleanup" EXIT

source ${DIR}/test_cuse

rm -f $STATE_FILE $VOLATILE_STATE_FILE 2>/dev/null

$SWTPM_EXE --tpm2 -n $VTPM_NAME
sleep 0.5
PID=$(ps aux | grep $SWTPM | grep -E "$VTPM_NAME\$" | gawk '{print $2}')

ps aux | grep $SWTPM | grep -v grep

kill -0 $PID
if [ $? -ne 0 ]; then
	echo "Error: CUSE TPM did not start."
	exit 1
fi

# Init the TPM
$CUSE_TPM_IOCTL -i /dev/$VTPM_NAME
if [ $? -ne 0 ]; then
	echo "Error: Could not initialize the CUSE TPM."
	exit 1
fi

kill -0 $PID 2>/dev/null
if [ $? -ne 0 ]; then
	echo "Error: CUSE TPM not running anymore after INIT."
	exit 1
fi

# Set locality 4 on the TPM
$CUSE_TPM_IOCTL -l 4 /dev/$VTPM_NAME
if [ $? -ne 0 ]; then
	echo "Error: CUSE TPM did not accept locality 4."
	exit 1
fi

# Set illegal locality 5 on the TPM
$CUSE_TPM_IOCTL -l 5 /dev/$VTPM_NAME
if [ $? -eq 0 ]; then
	echo "Error: CUSE TPM accepted locality 5."
	exit 1
fi

# Set locality 0 on the TPM
$CUSE_TPM_IOCTL -l 0 /dev/$VTPM_NAME
if [ $? -ne 0 ]; then
	echo "Error: CUSE TPM did not accept locality 0."
	exit 1
fi

# In locality 2 we can reset PCR 20
$CUSE_TPM_IOCTL -l 2 /dev/$VTPM_NAME
if [ $? -ne 0 ]; then
	echo "Error: CUSE TPM did not accept locality 2."
	exit 1
fi

exec 100<>/dev/$VTPM_NAME

# Need to set locality 0 or 3 for TPM2_Startup to work...
# TPM_Startup for TPM 1.2 worked in all localities
$CUSE_TPM_IOCTL -l 3 /dev/$VTPM_NAME
if [ $? -ne 0 ]; then
	echo "Error: CUSE TPM did not accept locality 3."
	exit 1
fi

# Startup the TPM
exec 100<>/dev/$VTPM_NAME
echo -en '\x80\x01\x00\x00\x00\x0c\x00\x00\x01\x44\x00\x00' >&100
RES=$(dd if=/proc/self/fd/100 2>/dev/null | od -t x1 -A n)
exp=' 80 01 00 00 00 0a 00 00 00 00'
if [ "$RES" != "$exp" ]; then
	echo "Error: Did not get expected result from TPM2_Startup(SU_Clear)"
	echo "expected: $exp"
	echo "received: $RES"
	exit 1
fi

# In locality 2 we can reset PCR 20
$CUSE_TPM_IOCTL -l 2 /dev/$VTPM_NAME
if [ $? -ne 0 ]; then
	echo "Error: CUSE TPM did not accept locality 2."
	exit 1
fi

# Reset PCR 20
echo -en '\x80\x02\x00\x00\x00\x1b\x00\x00\x01\x3d\x00\x00\x00\x14\x00\x00\x00\x09\x40\x00\x00\x09\x00\x00\x00\x00\x00' >&100
RES=$(dd if=/proc/self/fd/100 2>/dev/null | od -t x1 -A n -w128)
exp=' 80 02 00 00 00 13 00 00 00 00 00 00 00 00 00 00 01 00 00'
if [ "$RES" != "$exp" ]; then
	echo "Error: Could not reset PCR 20 in locality 2"
	echo "expected: $exp"
	echo "received: $RES"
	exit 1
fi

# In locality 1 we can NOT reset PCR 20
$CUSE_TPM_IOCTL -l 1 /dev/$VTPM_NAME
if [ $? -ne 0 ]; then
	echo "Error: CUSE TPM did not accept locality 1."
	exit 1
fi

# Reset PCR 20
echo -en '\x80\x02\x00\x00\x00\x1b\x00\x00\x01\x3d\x00\x00\x00\x14\x00\x00\x00\x09\x40\x00\x00\x09\x00\x00\x00\x00\x00' >&100
RES=$(dd if=/proc/self/fd/100 2>/dev/null | od -t x1 -A n -w128)
exp=' 80 01 00 00 00 0a 00 00 09 07'
if [ "$RES" != "$exp" ]; then
	echo "Error: Could reset PCR 20 in locality 1"
	echo "expected: $exp"
	echo "received: $RES"
	exit 1
fi

# Shut down TPM
$CUSE_TPM_IOCTL -s /dev/$VTPM_NAME
if [ $? -ne 0 ]; then
	echo "Error: Could not shut down the CUSE TPM."
	exit 1
fi

sleep 0.5

kill -0 $PID 2>/dev/null
if [ $? -eq 0 ]; then
	echo "Error: CUSE TPM should not be running anymore."
	exit 1
fi

if [ ! -e $STATE_FILE ]; then
	echo "Error: TPM state file $STATE_FILE does not exist."
	exit 1
fi

echo "OK"

exit 0
